# Generated by Django 2.2.6 on 2020-04-25 13:36

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=20)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=20)),
                ('g_pic', models.ImageField(upload_to='hh_good')),
                ('g_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_intro', models.CharField(max_length=200)),
                ('g_stock', models.IntegerField()),
                ('g_desc', tinymce.models.HTMLField()),
                ('is_delete', models.BooleanField(default=False)),
                ('g_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hh_good.TypeInfo')),
            ],
        ),
    ]
