# Generated by Django 2.2.6 on 2020-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh_good', '0002_goodinfo_g_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodinfo',
            name='g_unit',
            field=models.CharField(default='500g', max_length=50),
        ),
    ]
