# Generated by Django 2.2.6 on 2020-05-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh_good', '0003_goodinfo_g_unit'),
        ('hh_user', '0001_initial'),
        ('hh_cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardInfo',
            new_name='CartInfo',
        ),
    ]
