# Generated by Django 2.2.6 on 2020-04-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=10)),
                ('u_pwd', models.CharField(max_length=40)),
                ('u_phone', models.CharField(max_length=11)),
                ('u_email', models.CharField(default='', max_length=30)),
                ('u_real_name', models.CharField(default='', max_length=10)),
                ('u_addr', models.CharField(default='', max_length=100)),
                ('u_code', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
